name: "TCS Tecnoalarm"
description: "Tecnoalarm TCS integration"
version: "1.0.0"
slug: "tcs_tecnoalarm"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - type: share
    read_only: False
options:
  mqtt_config:
    mqtt_host: "localhost"
    mqtt_port: 1883
schema:
  mqtt_config:
    mqtt_host: str
    mqtt_port: int
    logins:
      - mqtt_username: str
        mqtt_password: str
  tcs_config:
    tcs_serial: str(0,9)
    logins:
      - tcs_username: str
        tcs_password: str
    tcs_token: "str?"

