name: "TCS Tecnoalarm"
description: "Tecnoalarm TCS integration"
version: "1.0.0"
slug: "tcs_tecnoalarm"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - type: share
    read_only: False
options:
  mqtt_host: "localhost"
  mqtt_port: 1883
  mqtt_username: "username"
  mqtt_password: "password"
  tcs_serial: "123456789"
  tcs_username: "username"
  tcs_password: "password"
schema:
  mqtt_host: str
  mqtt_port: int         
  mqtt_username: str  
  mqtt_password: str  
  tcs_serial: str    
  tcs_username: str  
  tcs_password: str 
